### ISSUE TITLE
Make the HacktoberfestProgressIndicator better.

### ISSUE THREAD

**Issue by kerk12** [kerk12/hacktoberfest_checker#3]
It's currently ugly. It needs to be not ugly :P.

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by kerk12** [comment]
@Abhijeet-sonkar Sure, go ahead :+1:

**Comment by Abhijeet-sonkar** [comment]
Can you provide the path of the file which need to be modified?

**Comment by kerk12** [comment]
https://github.com/kerk12/hacktoberfest_checker/blob/master/lib/widgets/hf_progress_indicator.dart
Also, when I say ugly, I mean the UI. The code also might need some fixes, but the UI needs most of the fixing.

**Comment by Abhijeet-sonkar** [comment]
hey @kerk12 ,
I was using your app but was unable to login .
The "set" button was  not working .
Could you provide instructions on how the user have to login?

**Comment by kerk12** [comment]
You don't need to login. You need to type your username in github and then it uses the GitHub API to pull data about your profile, your PRs etc...

In my case, I'd type `kerk12`
